version: 2
updates:
  - package-ecosystem: "terraform"
    directories:
      - "/terraform/environments/prod"
      - "/terraform/modules/server"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
